#!/bin/sh

# A dmenu wrapper script for system functions.

# For non-systemd init systems.
case "$(readlink -f /sbin/init)" in
	*runit*) hib="sudo -A zzz" ;;
	*openrc*) reb="sudo -A shutdown -r"; shut="sudo -A shutdown -p" ;;
esac

cmds="\
🔒 lock		waylock
🚪 leave hyprland	kill -TERM $(pgrep -u $USER "\bHyprland$")
🔃 reboot	doas reboot
💀 shutdown 	doas shutdown now"

choice="$(echo "$cmds" | cut -d'	' -f 1 | wofi --show dmenu)" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
